shell = "/bin/zsh"

import = ["~/.config/alacritty/color.toml"]

[window]
padding = { x = 10, y = 10 }
opacity = 0.85

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 11

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
blink_interval = 1000
blink_timeout = 15
thickness = 0.18
